version: '3'
services:
  app:
    container_name: user_app
    build:
      context: ./docker/nuxt.js
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ./docker/nuxt.js/src:/src:cached
      # exclude volumes
      - /src/app/node_modules
    tty: true
    stdin_open: true
    # Hot Module Replacement (HMR) is enable for virtual box.
    environment:
      - CHOKIDAR_USEPOLLING=true